boostcampwm-2021/web14-salondesrefuses

server/src/app.module.ts
server/src/artWork/artWork.repository.ts
server/src/user/controller/user.controller.ts
server/src/user/service/user.service.ts
server/src/user/user.module.ts
server/src/user/user.repository.ts

- 사용자가 등록한 모든 artwork 조회 API 구현
close #60

feat: 사용자가 등록한 모든 artwork 조회 API 구현 - #60

---

client/components/Artwork/ArtworkModal/index.tsx
client/components/Artwork/ArtworkModal/style.ts
client/hooks/useInputArtwork.ts
client/hooks/useTest.ts
client/interfaces.ts
client/utils/networking.ts
client/utils/parseCookie.ts

- 작품 추가 api 연결
- 성공 시 메인 페이지로 라우팅
작품 추가 성공 / 실패 시 모달같은걸로 UI를 그려주면 좋을것 같습니다.
결과화면 스크린샷
close #106

feat: 작품 추가 api 등록 - #106

---

client/components/Artwork/ArtworkModal/index.tsx
client/components/Artwork/NewArtwork/index.tsx
client/components/Artwork/Uploader/index.tsx
client/components/Auction/AuctionList.tsx
client/components/Header/headerStyles.tsx
client/hooks/useControlModalPosition.ts
client/hooks/useInputArtwork.ts
client/pages/artwork/post.tsx
client/utils/networking.ts
server/package-lock.json
server/src/auction/controller/auction.controller.ts

리뷰받은 내용 반영하고 머지할때 나왔던 내용들 반영했습니다아

refactor: additional tasks

---

server/src/artwork/artwork.entity.ts
server/src/artwork/controller/artwork.controller.ts
server/src/artwork/dto/artworkDTOs.ts
server/src/artwork/service/artwork.service.ts
server/src/auth/guard/CustomAuthGuard.ts

작품 등록 api 개선
custom gaurd 에서 request에 user 넣어주도록 함! 
close #128

feat: 작품 등록 api 개선 - #128

---

client/components/Exhibition/LabelInput.tsx
client/components/Exhibition/style.ts
client/pages/exhibition/index.tsx
client/pages/exhibition/post.tsx

post 아트워크 페이지 레이아웃 구현
close #135

feat: post 아트워크 페이지 레이아웃

---

client/components/Artwork/ArtworkModal/ArtworkFilter.tsx
client/components/Artwork/ArtworkModal/index.tsx
client/components/Artwork/NewArtwork/style.ts
client/components/Auction/AuctionList.tsx
client/components/Card/index.tsx
client/components/Card/style.ts
client/components/Home/Pc/MainCarousel.tsx
client/components/Home/Pc/styles.ts
client/components/common/RequireLoginModal.tsx
client/constants/card-type.ts
client/constants/fakeDatas.ts
client/hooks/useControlModalPosition.ts
client/hooks/useHandleRequireLoginModal.ts
client/pages/artwork/result.tsx
client/pages/exhibition/index.tsx
client/utils/networking.ts
client/utils/setColorFromImage.ts
server/package-lock.json

드래그 방식 결정나고 컴포넌트 구조가 대충 나와야 다음 작업을 할 수 있을것 같으요..
충돌도 무서운데 그보다 뭘 몰라서 에디터쪽 작업을 할 수가 없었음
원래 메타마스크 연동하고 결과페이지 만들라했는데
뭐만 할라하면 터져서 결국 그거 깨작깨작 고침
Card 만들때 쓸 인터페이스가 ExhibitionCardProps, AuctionCardProps 이렇게 두개인데 이미지 속성 이름이 달라서 잘 안됩니다..
그리고 auction list api 올때 배열이 [ { artwork : 아트워크 데이터}, ... ] 이런식으로 한번 감싸져서 오던데 확인 한번만 해주라
지금은 일단 클라이언트에서 map돌려서 artwork 안에 있는거 빼서 쓰고있으요
아무튼 인터페이스 한번 싹 맞출 필요가 있음.. 지금 굉장히 난장판이야
내일은 에디터 하고 진짜 메타마스크 붙인다.
- 스크린샷은 sqlGenerator로 만들고 이미지는 따로 하나하나 넣어줘서 찍은겁니다아
- Newest일때랑 Deadline일때랑 리스트 순서 다른거 확인
Not close this issue.

feat: 로그인 필요한 기능의 경우 모달 추가, api 싱크 안맞는 interface 수정 등 - #140

---

client/components/Exhibition/Editor/EditorElement.tsx
client/components/Exhibition/Editor/index.tsx
client/components/Exhibition/Editor/utils.ts
client/components/Home/Pc/styles.ts
client/pages/exhibition/post.tsx

에디터 초안 / 사각형 넣기 / 드래그
기능을 구현하면서 만났던 어려웠던 점.
drag가 아닌 mouse로 해야함!
포지션에 주의
close #142

feat: 에디터 초안 / 사각형 넣기 / 드래그 - #142

---

client/constants/auction-state.ts
client/constants/card-type.ts
client/constants/fakeDatas.ts
server/.env.example
server/src/auth/service/auth.service.ts

fix: 버그 수정

---

server/src/artwork/artwork.repository.ts
server/src/artwork/controller/artwork.controller.ts
server/src/artwork/service/artwork.service.ts
server/src/artwork/swagger/index.ts
server/src/exhibition/exhibition.repository.ts
server/src/user/controller/user.controller.ts
server/src/user/dto/userDTO.ts
server/src/user/service/user.service.ts
server/src/user/swagger/index.ts
server/src/user/user.module.ts

feat: 마이페이지 API 구현 - #148

---

client/components/Artwork/ArtworkModal/ArtworkFilter.tsx
client/components/Artwork/ArtworkModal/style.ts
client/components/Artwork/NewArtwork/index.tsx
client/components/Artwork/NewArtwork/style.ts
client/components/Auction/AuctionList.tsx
client/components/Card/style.ts
client/components/Exhibition/style.ts
sqlGenerator/README.md
sqlGenerator/index.js

Fix: css 간단 수정과 sql 제너레이터 개선

---

client/components/Exhibition/Editor/EditorElement.tsx
client/components/Exhibition/Editor/resizeFunctions.ts
client/components/Exhibition/Editor/utils.ts

전반적인 구현 내용
리사이즈 1차적으로 구현했습니다.
- 점도 같이 움직이기
- 이미지, 텍스트 대응
- 셀렉트 오류 수정
해야함!!!
close #이슈넘버

feat: Resize 1차 구현 완료

---

client/components/Exhibition/Editor/Editor.tsx
client/components/Exhibition/Editor/EditorElement.tsx
client/components/Exhibition/Editor/utils.ts
client/package-lock.json
client/store/GlobalStore.tsx

resize시 dots 오류 해결 / selectable 수정 / input 반쪽 해결
input 부분이 걱정이 많습니다
결과화면 스크린샷

fix: #134 - resize시 dots 오류 해결 / selectable 수정 / input 반쪽 해결

---

client/components/Artwork/ResultDetail/index.tsx
client/pages/artwork/result/index.tsx
client/utils/networking.ts

feat:  artwork 등록 결과 페이지 레이아웃 작업 - #173

---

client/components/Exhibition/EditorPage/Editor/index.tsx
client/components/Exhibition/EditorPage/EditorElement/index.tsx
client/components/Exhibition/EditorPage/EditorElement/utils.ts
server/package-lock.json

이미지 리사이즈 / input 드래거블
더블클릭으로 input 변경하시면 됩니다
결과화면 스크린샷
close #171

feat: #171 - 이미지 리사이즈 / input 드래거블

---

server/src/artwork/artwork.repository.ts
server/src/artwork/dto/artworkDTOs.ts
server/src/auction/controller/auction.controller.ts
server/src/cronTask/ethereum/abi.json
server/src/cronTask/ethereum/address.json
server/src/exhibition/controller/exhibition.controller.ts
server/src/exhibition/dto/exhibitionDTO.ts
server/src/exhibition/exhibition.entity.ts
server/src/exhibition/exhibition.repository.ts
server/src/exhibition/service/exhibition.service.ts

전시회 response DTO 변경
close #200

feat: 전시회 response DTO 변경

---

client/components/Auction/ItemDetail/index.tsx
client/components/Auction/TrendHistory/index.tsx
server/src/auction/auction.gateway.ts
server/src/auction/auction.repository.ts
server/src/auction/dto/auctionDTOs.ts
server/src/auctionHistory/auctionHistory.entity.ts
server/src/auctionHistory/auctionHistory.module.ts
server/src/auctionHistory/auctionHistory.service.ts
server/src/completedAuction/completedAuction.entity.ts
server/src/completedAuction/completedAuction.service.ts
server/src/user/controller/user.controller.ts
server/src/user/swagger/index.ts

- 경매 작품 조회 API 수정
- 사용자 프로필 수정 API 폼데이터 명세 추가
- close #206

fix: 경매 작품 조회 API 수정

---

client/components/Auction/ItemDetail/index.tsx
client/interfaces.ts
server/src/artwork/artwork.entity.ts
server/src/artwork/artwork.repository.ts
server/src/auction/auction.entity.ts
server/src/auction/auction.repository.ts
server/src/auction/auction.service.ts
server/src/auction/dto/auction.dto.ts
server/src/auction/gateway/auction.gateway.ts
server/src/category/category.repository.ts
server/src/exhibition/exhibition.service.ts
server/src/interestArtwork/interestArtwork.entity.ts
server/src/interestArtwork/interestArtwork.repository.ts
server/src/user/user.repository.ts

fix: 백엔드 API 개선

---

server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/cronTask/crontask.controller.ts
server/src/utils/port/port.controller.ts
server/src/utils/port/port.module.ts

- 무중단 배포를 위한 port controller 구현
close #이슈넘버

feat: port controller 구현

---

client/components/Auction/BidTable/index.tsx

client 빌드시 catch 부분 error 변수가  known이라서 에러 발생 any 타입 넣어줌으로써 해결

fix: error any 타입 추가

---

server/src/auctionHistory/auctionHistory.repository.ts
server/src/auctionHistory/auctionHistory.service.ts
server/src/completedAuction/completedAuction.service.ts
server/src/cronTask/crontask.service.ts

CompletedAuction 서비스 에러 해결 
- bidder inner 조인에서 left outer로 변경
- transaction 제거

fix: CompletedAuction 서비스 에러 해결 

---

server/package-lock.json
server/package.json
server/src/artwork/artwork.service.ts
server/src/artwork/test/artwork.spec.ts
server/src/auction/auction.controller.ts
server/src/auction/test/auction.spec.ts
server/src/exhibition/exhibition.controller.ts
server/src/exhibition/test/exhibition.spec.ts
server/src/user/test/user.spec.ts

- 백엔드 통합 테스트 코드 작성
- 이미지 mocking이 잘 되지 않아 post는 실패합니다..

feat: 테스트 코드 작성

---

client/components/Exhibition/EditorPage/index.tsx
client/components/Exhibition/ExhbitionDetail/ExhibitionContents.tsx
client/hooks/useInputExhibition.ts
client/service/networking.ts

- text 전시회 에딧에서 사용할 시에 아직 버그 유지
전반적인 구현 내용
DangerouslyHTML로 사용
결과화면 스크린샷
close #이슈넘버

feat: patch -> put / text 깨지는것

---

client/components/Exhibition/EditorPage/Editor/index.tsx
client/components/Exhibition/EditorPage/Editor/types.ts
client/components/Exhibition/EditorPage/EditorElement/index.tsx
client/components/Exhibition/EditorPage/index.tsx
client/constants/toast-message.ts
client/pages/exhibition/edit.tsx
client/pages/exhibition/post.tsx

에디터 버그들 중 
텍스트 여러줄일때 수정 깨지는거 방지
수정 페이지 url 접속시 막아주기
에디팅 도중 폼테그 돌아가도 현상유지
구현함요
근데 url 접속은 아예 자체에 버그가있.....
기능을 구현하면서 만났던 어려웠던 점.
close #이슈넘버

fix: Editor Bug 특집 2탄

---

client/components/Exhibition/EditorPage/Editor/index.tsx
client/components/Exhibition/EditorPage/EditorElement/index.tsx
client/components/Exhibition/ExhbitionDetail/ExhibitionContents.tsx
client/components/Exhibition/ExhbitionDetail/ExhibitionLazyImage.tsx
client/components/common/Card/style.ts
client/constants/toast-message.ts

이미지, 엘리먼트 수 제한
삭제 버그 해결
lazy loading
하루 더 코딩할 수 있게 해줘서 고맙습니다
- close #264

fix: 에디터 버그잡기 + 성능개선 3편
